export const books = [
  {
    title: "The Silent Ocean",
    author: "Emily Carter",
    ISBN: "978-1-56619-909-4",
    pages: 320,
    price: 19.99,
    publisher: "Seabreeze Publishing",
    year: 2021,
    language: "English",
    category: "Fiction",
  },
  {
    title: "Mastering JavaScript",
    author: "John Doe",
    ISBN: "978-0-596-52068-7",
    pages: 450,
    price: 39.99,
    publisher: "TechWorld Publications",
    year: 2022,
    language: "English",
    category: "Programming",
  },
  {
    title: "The Mystery of Time",
    author: "Samantha Harris",
    ISBN: "978-3-16-148410-0",
    pages: 285,
    price: 22.5,
    publisher: "Chrono Books",
    year: 2020,
    language: "English",
    category: "Science Fiction",
  },
  {
    title: "Python for Data Science",
    author: "Michael O'Neil",
    ISBN: "978-1-4919-1889-0",
    pages: 500,
    price: 45.0,
    publisher: "DataWorks",
    year: 2021,
    language: "English",
    category: "Programming",
  },
  {
    title: "Gardens of the Mind",
    author: "Alice Thompson",
    ISBN: "978-1-84022-699-5",
    pages: 200,
    price: 17.99,
    publisher: "Green Thumb Press",
    year: 2018,
    language: "English",
    category: "Non-fiction",
  },
  {
    title: "Understanding AI",
    author: "David Stone",
    ISBN: "978-1-84953-221-3",
    pages: 320,
    price: 30.0,
    publisher: "Future Tech",
    year: 2023,
    language: "English",
    category: "Technology",
  },
  {
    title: "Winds of Change",
    author: "Lily Kingston",
    ISBN: "978-1-86064-987-2",
    pages: 400,
    price: 24.99,
    publisher: "Whirlwind Books",
    year: 2019,
    language: "English",
    category: "Historical Fiction",
  },
  {
    title: "The Culinary Art",
    author: "Gordon Ramsey",
    ISBN: "978-0-684-84328-5",
    pages: 150,
    price: 29.95,
    publisher: "Foodie Press",
    year: 2020,
    language: "English",
    category: "Cooking",
  },
  {
    title: "Exploring the Universe",
    author: "Dr. Neil Tyson",
    ISBN: "978-1-250-08899-0",
    pages: 370,
    price: 32.5,
    publisher: "Cosmic Reads",
    year: 2021,
    language: "English",
    category: "Science",
  },
  {
    title: "The Way of Kings",
    author: "Brandon Sanderson",
    ISBN: "978-0-765-36527-9",
    pages: 1007,
    price: 39.9,
    publisher: "Tor Books",
    year: 2010,
    language: "English",
    category: "Fantasy",
  },
];
